ubtue/zotkat-translators

ubtue_Cambridge Core.js
scraping keywords from website - only for this journal -  instead of using structure metadata tag citation_keywords due to wrong keywords https://github.com/ubtue/DatenProbleme/issues/1883
=> scraping keywords from website - only for this journal - 

ubtue_CRI.js
additionally Tests were added and the "Complete Issue" is excluded from search
=> issue information found again ubtue/DatenProbleme#1959 

ubtue_scholarlypublishing.js
ubtue/Datenprobleme#1972
ubtue/Datenprobleme#1973
=> delete URL if DOI, change check for LF

ubtue_Atypon_Journals.js
=> Tranlator for Liverpool University press ubtue/Datenprobleme#1964

ubtue_OpenEdition Journals.js
preview not imported second time if already in abstractNote; change issue number to volume number for 0335-5985
=> ubtue/DatenProbleme#1921 ubtue/DatenProbleme#1922

ubtue_RHPR.js
detectWeb: Regex angepasst
invokeEMTranslator: Seitenzahlen Error fixed
=> address https://github.com/ubtue/DatenProbleme/issues/2051

ubtue_Springer Link.js
Quelltext nutzt neue Klassen, weshalb der XPath für den Mehrfach Export angepasst werden musste. Ich habe die Ergänzung entsprechend kommentiert @jriedl
=> addresses https://github.com/ubtue/DatenProbleme/issues/2056

ubtue_Allied_Academies.js, ubtue_trends_and_issues_criminology.js
added fictitious ISSN, normalized upper case titles, removed LF tag
=> Implemented Feedback to https://github.com/ubtue/DatenProbleme/issues/2095

ubtue_pica3.js
https://github.com/ubtue/DatenProbleme/issues/2095
=> pica3 translator updated for fake issn krim

ubtue_trends_and_issues_criminology.js
https://github.com/ubtue/DatenProbleme/issues/2094#issuecomment-2098493618
=> adjusting artikelID from tag to note

ubtue_Open Journal Systems Standard.js, ubtue_Springer Link.js
Bei dem Issue Springer Link hatte ich fälschlicherweise die Issue Nr. 2048 angegeben.
https://github.com/ubtue/DatenProbleme/issues/2118
https://github.com/ubtue/DatenProbleme/issues/2048
=> Issue 2118 und 2048

ubtue_APCJ.js
Opening PR so this can be discussed in our upcoming meeting
=> New Translator

ubtue_Wiley Online Library.js
addressing https://github.com/ubtue/DatenProbleme/issues/2045
=> copying changes from ZotAut

ubtue_Taylor and Francis+NEJM.js, ubtue_pica3.js
implimenting changes from https://github.com/ubtue/zotero-translators/commit/27d2c824a9e86eff4c8bb840cc1a80f2f639bfb2
=> addresses https://github.com/ubtue/DatenProbleme/issues/2188, 

ubtue_Quaderni di storia religiosa medievale.js
Adjusting the selectors for getSearchResults
=> addresses https://github.com/ubtue/DatenProbleme/issues/2196

ubtue_Open Journal Systems Standard.js
…s://github.com/ubtue/DatenProbleme/issues/2206
=> Zwinglia Issues

ubtue_OPUS_uniFrankfurt.js
12e51a3ed8ea8e35e014ead71b6e38b003c89c9f contains the wrong URL, I would leave it like that unless necessary? Correct would be https://github.com/ubtue/DatenProbleme/issues/2237
=> ZotKat Issues

ubtue_Beltz.js
addresses https://github.com/ubtue/DatenProbleme/issues/2244
=> new translator ubtue_Beltz.js

ubtue_Karolinum_Press.js
https://github.com/ubtue/DatenProbleme/issues/2246
=> new translator ubtue_Karolinum_Press.js, 

ubtue_Equip.js
https://github.com/ubtue/DatenProbleme/issues/2245
=> new translator ubtue_Equip.js

ubtue_Journal of Religion and Society.js
https://github.com/ubtue/DatenProbleme/issues/2165
=> some improvement for pages and 500 error

ubtue_SAGE Journals.js
and https://github.com/ubtue/DatenProbleme/issues/2256
=> addresses https://github.com/ubtue/DatenProbleme/issues/1620 

ubtue_EBSCO Discovery Layer.js
See https://github.com/ubtue/DatenProbleme/issues/2240
=> Adding tag for reviews

ubtue_word&world.js
See: https://github.com/ubtue/DatenProbleme/issues/2272
=> Updated Word & World Translator

ubtue_DeGruyter.js
See: https://github.com/ubtue/DatenProbleme/issues/2279
=> Adjusted target to match url

ubtue_vandenhoeck_ruprecht.js
V&R seems to have blocked me - while I'm still able to access their website via my browser, the Zotero scaffold is giving me a status 403 error. I think I was able to do sufficient testing on this adjusemt before the block though.
=> adjusted convertToJournal function for lacking metadata

ubtue_word&world.js
See: https://github.com/ubtue/DatenProbleme/issues/2272#issuecomment-2834342417
=> extracting fall issue number and adjusted subtitle delimiter

ubtue_Journal_Scriptural_Reasoning.js
addresses https://github.com/ubtue/DatenProbleme/issues/2282
=> new translator ubtue_Journal_Scriptural_Reasoning.js

ubtue_DeGruyter.js
See: https://github.com/ubtue/DatenProbleme/issues/2279
=> adding RezensionsTagPica for Review Articles

ubtue_Cairn.info.js, ubtue_OPUS_uniAugsburg.js
addresses https://github.com/ubtue/DatenProbleme/issues/2290
=> new translator ubtue_OPUS_uniAugsburg.js

ubtue_DeGruyter.js
Noticed a changed HTML-structure preventing multiple to be detected, while working on: https://github.com/ubtue/DatenProbleme/issues/2279
=> adjusted detectWeb for multiple

ubtue_EBSCO Discovery Layer.js
See:
https://github.com/ubtue/DatenProbleme/issues/2229
and
https://github.com/ubtue/DatenProbleme/issues/2230
respectively.
=> extracting italian abstract and author keywords

ubtue_EBSCO Discovery Layer.js
See: https://github.com/ubtue/DatenProbleme/issues/2231
=> replacing issue with volume for issn 0075-2541

ubtue_georgefox_tudublin.js
See: https://github.com/ubtue/DatenProbleme/issues/2219
=> added RezensionstagPica

ubtue_TheoWeb.js
Extended translator to also extract metadata from
- https://www.theo-web.de/zeitschrift/ (Archive 2002-2017)
- https://openjournals.fachportal-paedagogik.de/theo-web/issue/archive (new website from 2025)
=> support additional journal websites, see ubtue/DatenProbleme#2337
